config/routes.rb
Blog::Application.routes.draw do
  
  resources :comments do
    member do
      get "edit", to: "comments#edit", as: "edit"
      get "delete", to: "comments#destroy", as: "delete"
      post "update",to: "comments#update", as: "update"
    end
    collection do
      get "show", to: "comments#show", as: "show"
    end
  end

  resources :users do
    member do
      get "edit"
      get "delete", to: "user#destroy", as: "delete"
      post "update"
    end
  end

  resources :articles do
    member do
      get "edit"
      get "delete", to: "articles#destroy", as: "delete"
      post "update"
    end
  end

  resources :friendships do
    member do
      get "block", to: "friendships#block", as: "block"
      get "delete", to: "friendships#destroy", as: "delete"
      get "make", to: "friendships#create", as: "make"

      get "accept", to: "friendships#accept", as: "accept"
      get "check", to: "friendships#check", as: "check"
    end
  end

  
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'page/index'
  root to: 'page#index'

  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  belongs_to :user
  has_many :comment
  
  cattr_reader :per_page
  
  @@per_page = 100

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
 
  def new
    p "ArticlesController new"
    puts session[:user_id]
  end


  def index
    user = @user=User.find(current_user)
    @articles = current_user.articles.paginate(:page => params[:page])

    p "ArticlesController index user_id" + @user.id.to_s
    myfriends = Friendship.where(friendA: @user.id )
    myfriends = myfriends.concat( Friendship.where(friendB: @user.id ) )
    @friends = []
    myfriends.each do |f|

      if f.status.to_s != "4"  # not blocked
        if (f.friendA.to_s == @user.id.to_s)
          u = User.find(f.friendB) 
        else
          u = User.find(f.friendA)
        end
        @friends.push(u)
      end
      if u
      ua = u.articles.paginate(:page => params[:page])
      
      @articles=@articles.concat( ua )
      end
    end

    #@articles = @articles.contact()
    #puts "!! ArticlesController index"+ current_user.articles.length.to_s + " " + @articles.empty?.to_s
  end
  
  def show
    @article = Article.find(params[:id])
    #render nothing: true
    render 
  end
  
  def edit
    p "! articlesController edit"
    @article = Article.find(params[:id])
    #render nothing: true
    render 
  end
  

  def update
    p "!! articlesController update"

    @article = Article.find(params[:id])
    @article.user_id= current_user.id
    @article.update_attributes(params[:article])
    
    redirect_to  :action => 'index'
    #render nothing: true
  
  end
  

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to  :action => 'index'
  end

  def new_article
    params.require(:article).permit(:text, :title , :user_id )
  end

 def create
  #params[:article]
  #params[:article][:user] = Integer(params[:article][:user])

  @article = Article.new(new_article)
  @article.user_id= current_user.id
  @article.save
  redirect_to  :action => 'index'
 end
   
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="article_<%=article.id%>" class="article">
	<div class="article-info">
		<br>
		<h3><%=  article.title %></h3>
		<% @author = User.find(article.user_id) %>
		<span class="fl" ><%=  " Author: " + @author.first_name + " " + @author.last_name  %> </span>
		<span class="space"></span>
		<span class="fl space"><%= button_to "Comment it", new_comment_path(article) , :class => "btn btn-primary btn-xs", :method => :get  %></span>
		<%if @author.id == @user.id %>
			<span class="fl space"><%= button_to "Edit", edit_article_path(article) , :class => "btn btn-primary btn-xs", :method => :get  %></span>		
			<span class="fl space"><%= button_to "Remove", delete_article_path(article) , :class => "btn btn-primary btn-xs", :method => :get  %></span>		
		<%else%>
		<% 
			@relations = Friendship.where( "friendA = ? OR  friendB = ?" , session[:user_id], false) 
			changeText(session, @author, @relations ) 
		%>
		  <div class="fl makeFriendship space" >
	      <%= button_to @makebtn, make_friendship_path( @author.id) , 
	            :class => "btn btn-warning btn-xs ", 
	            :disabled => @makedis,
	            :method => :get  %></div>    
	      <div class="fl blockThisPeople space" >
	      <%= button_to @delbtn, delete_friendship_path(@author.id) , 
	            :class => "btn btn-info btn-xs",
	            :disabled => @deldis,
	            :method => :get  %></div>    
	      <div class="fl blockThisPeople space" >
	      <%= button_to @blkbtn, block_friendship_path(@author.id) , 
	            :class => "btn btn-danger btn-xs",
	            :disabled => @blkdis,
	            :method => :get  %></div>     
		<%end%>
		<br>
		<br>
	</div>
	
	<p>
		<%= article.text %>

	</p>
</div>

app/views/articles/_getting_started.html.erb
<div id="getting_started">
	<h1>No avaliable post</h1>
	
</div>

app/views/articles/create.html.erb
<h1>Created</h1>

app/views/articles/edit.html.erb
<br>
<br>
<h1>Edit Article</h1>

<%= form_for :article , url: {action: "update"}  do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
   
    
  </p>
 
  <p>
    <%= f.label :text %>
    <br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit :value => "Update" %>
  </p>
<% end %>



<%= button_to "Remove", delete_article_path(params[:id]) , :class => "btn btn-primary btn-xs", :method => :get  %>

app/views/articles/index.erb
<br>
<br>
<h1  class="header" >List All Article</h1>

<div class="fieldset">
  <div class="legend">Posts overview</div>
  <div class="legend-content">
  <%= button_to "Write a new post", new_article_path, :class => "topbar btn btn-primary btn-xs", :method => :get  %>
    
    <div> Total post: <%= @articles.length.to_s %> </div>
    
    <% if !@articles %>
       <%= render :partial => 'getting_started' %>
    <% else %>
    <div id="campaigns">
      <%= render @articles %>
      <%= will_paginate @articles %>      
    </div>
    <% end %>

    
  </div>
</div>

app/views/articles/new.html.erb
<br>
<br>
<h1>New Article</h1>

<%= form_for :article , url: {action: "create"}  do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
   
    
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.erb
<br> 
<br> 
<h2>Post Published</h2> 
<br> 
<%= link_to 'Home', root_path %> 