config/routes.rb
Blog::Application.routes.draw do
  
  resources :comments do
    member do
      get "edit", to: "comments#edit", as: "edit"
      get "delete", to: "comments#destroy", as: "delete"
      post "update",to: "comments#update", as: "update"
    end
    collection do
      get "show", to: "comments#show", as: "show"
    end
  end

  resources :users do
    member do
      get "edit"
      get "delete", to: "user#destroy", as: "delete"
      post "update"
    end
  end

  resources :articles do
    member do
      get "edit"
      get "delete", to: "articles#destroy", as: "delete"
      post "update"
    end
  end

  resources :friendships do
    member do
      get "block", to: "friendships#block", as: "block"
      get "delete", to: "friendships#destroy", as: "delete"
      get "make", to: "friendships#create", as: "make"

      get "accept", to: "friendships#accept", as: "accept"
      get "check", to: "friendships#check", as: "check"
    end
  end

  
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'page/index'
  root to: 'page#index'

  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  #accepts_attributes :first_name, :last_name, :email , :name ,  :password

  has_many :articles, dependent: :destroy

  validates :first_name,
            presence: true
  validates :last_name,
            presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
  def to_s
    "#{first_name} #{last_name}"
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
   
    respond_to do |format|
      format.html  #index.html.erb
      format.json { render json: @users }
      format.xml { render xml: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def new_person
    params.require(:user).permit(:first_name, :last_name, :email, :name, :password_digest )
  end

  def create
    p ">>>>>> create  " + params[:password_digest].to_s
    @user = User.new(new_person)

    respond_to do |format|
      if @user.save
        p ">>>>>> user created"
        format.html { redirect_to  "/login", notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        p ">>>>>> user created fail"
        p @user.errors
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(new_person)
        p "updated!"
        format.html { redirect_to "/login", notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        p "updated fail!"
        p @user.update_attributes(new_person)
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<%#=user.id.to_s  + " " + params.to_s + " " + session.to_s %>
<div id="user_<%=user.id%>" class="user">

<%
  changeText(session, user, @relations )
%>

<%#= curFriendship[:status] %>
  <div class="user-info">
    <h3><%= user.name %></h3>
    <span class="fl friendName" ><%= user.first_name + " " + user.last_name  %> </span>
    <%if params[:controller]=="friendships" %>
      <div class="fl makeFriendship space" >
      <%= button_to @makebtn, make_friendship_path(user.id) , 
            :class => "btn btn-warning btn-xs ", 
            :disabled => @makedis,
            :method => :get  %></div>    
      <div class="fl blockThisPeople space" >
      <%= button_to @delbtn, delete_friendship_path(user.id) , 
            :class => "btn btn-info btn-xs",
            :disabled => @deldis,
            :method => :get  %></div>    
       <div class="fl blockThisPeople space" >
      <%= button_to @blkbtn, block_friendship_path(user.id) , 
            :class => "btn btn-danger btn-xs",
            :disabled => @blkdis,
            :method => :get  %></div>    
    
  <%else%>
   <span class="edituser space" >
   <%= button_to "Edit", edit_user_path(user.id) , 
            :class => "btn btn-primary btn-xs", 
            :method => :get  %></span>    
   <span class="deleteuser space" >

   <%= button_to "Delete", delete_user_path(user.id) ,
            :class => "btn btn-danger btn-xs",
            :method => :get  %></span>    
  <%end%>    
</div>
<br>

app/views/users/edit.html.erb
<br>
<br>
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> 
<!-- | -->
<%#= link_to 'Login', login_path %>

app/views/users/index.html.erb
<br>
<br>
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<br>
<br>

<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<br>
<br>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %>
<!--  | -->
<%#= link_to 'Login', login_path %>