config/routes.rb
Blog::Application.routes.draw do
  
  resources :comments do
    member do
      get "edit", to: "comments#edit", as: "edit"
      get "delete", to: "comments#destroy", as: "delete"
      post "update",to: "comments#update", as: "update"
    end
    collection do
      get "show", to: "comments#show", as: "show"
    end
  end

  resources :users do
    member do
      get "edit"
      get "delete", to: "user#destroy", as: "delete"
      post "update"
    end
  end

  resources :articles do
    member do
      get "edit"
      get "delete", to: "articles#destroy", as: "delete"
      post "update"
    end
  end

  resources :friendships do
    member do
      get "block", to: "friendships#block", as: "block"
      get "delete", to: "friendships#destroy", as: "delete"
      get "make", to: "friendships#create", as: "make"

      get "accept", to: "friendships#accept", as: "accept"
      get "check", to: "friendships#check", as: "check"
    end
  end

  
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'page/index'
  root to: 'page#index'

  
  

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friendships }
    end
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
    @friendship = Friendship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friendship }
    end
  end

  # GET /friendships/new
  # GET /friendships/new.json
  def new
    @relations=[]
    @a = session[:user_id].to_i
    #p "FriendshipsController new @a:" + @a.to_s
    if Friendship.where(friendA:  @a)[0]
      @relations=@relations.concat( Friendship.where(friendA:  @a))
    end

    if Friendship.where(friendB:  @a)[0]
      @relations=@relations.concat( Friendship.where(friendB:  @a))
    end
  

    @users = User.all
    #p "FriendshipsController @users length: " + @users.length.to_s

    @users.delete(current_user)  # remove myself
    #p "FriendshipsController @users length: " + @users.length.to_s 

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friendship }
    end
  end

  # GET /friendships/1/edit
  def edit
    @friendship = Friendship.find(params[:id])
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @a = session[:user_id].to_s
    @b = params[:id].to_s
    exist = 0
    
    Friendship.all.each do |f|
        if (f.friendA.to_s==@a.to_s  && f.friendB.to_s == @b.to_s) || (f.friendA.to_s==@b.to_s  && f.friendB.to_s==@a.to_s) 
            exist = 1
            if f.status==1
              f.update_attributes( :status => 2)
            end
            break
        end
    end

# create and correct friend ship
    
    if exist == 0  
      @friendship = Friendship.new()
      @friendship.friendA=@a # FriendA is current user
      @friendship.friendB=@b # this is list friend ,  means FriendB
      @friendship.accepted = false
      @friendship.status = 1   
      @friendship.permit(:friendA,:friendB,:accepted,:status)
      @friendship.save
      # 0 => no relation   , 1 waiting answer , 2 bidirection , 4 block  , 
    else

    end

     redirect_to :action => "new"
    
  end

  def update
    @friendship = Friendship.find(params[:id])

    respond_to do |format|
      if @friendship.update_attributes(params[:friendship])
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end

  end
  
  def block
      
      @a = session[:user_id].to_s
      @b = params[:id].to_s

      @friendship = Friendship.where( friendA: @a , friendB: @b)[0] || Friendship.where( friendA: @b , friendB: @a)[0] 
      @friendship.update_attributes( :status => 4)
      
      respond_to do |format|
        format.html { redirect_to request.env["HTTP_REFERER"] }
        format.json { head :no_content }
      end     
  end


  def destroy
    @a = session[:user_id].to_s
    @b = params[:id].to_s

    @friendshipA = Friendship.where( friendA: @a , friendB: @b)[0] 
    @friendshipB = Friendship.where( friendA: @b , friendB: @a)[0] 
    
    
    if @friendshipA
      @friendshipA.destroy
    end 
    if @friendshipB
      @friendshipB.destroy
    end 
    

    respond_to do |format|
      format.html { redirect_to request.env["HTTP_REFERER"] }
      format.json { head :no_content }
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper

 def  changeText(session, user, relations )
 	#p "FriendshipsHelper changeText"
 	
 	  @a = session[:user_id]
	  @b =  user.id 
	  curFriendship = { id: 0 , friendA: 0, friendB: 0, status: 0, accepted: false  }
	  relations.each do |f|

	    if f[:friendA].to_s == user.id.to_s || f[:friendB].to_s == user.id.to_s 
	        curFriendship = f
	      break
	    end
	  end
	 
	  case curFriendship[:status].to_s
	    when "0"
	      @makebtn = "Make friendship"
	      @delbtn = "Breake relation"
	      @blkbtn = "Block this person"

	      @makedis = false
	      @deldis = true
	      @blkdis = true
	    when "1"
	      @makebtn = "Waiting for accept"
	      @delbtn = "Remove apply"
	      @blkbtn = "Block this person"
			
	      @makedis = true
	      @deldis = false
	      @blkdis = false
	    when "2"
	      @makebtn = "you are friends"
	      @delbtn = "Break relation"
	      @blkbtn = "Block this person"

	      @makedis = true
	      @deldis = false
	      @blkdis = false
	    when "4"
	      @makebtn = "This person blocked"
	      @delbtn = "Break relation"
	      @blkbtn = "Block this person"

	      @makedis = true
	      @deldis = false
	      @blkdis = true
	    else
	      @makebtn = "Make friendship"
	      @delbtn = "Break relation"
	      @blkbtn = "Block this person"

	      @makedis = false
	      @deldis = false
	      @blkdis = false
	    end  
		
		if curFriendship[:friendA].to_s != @a.to_s  && curFriendship[:status]==1
      	  @makebtn = "Accept invitation"
      	  @makedis = false
      	  @deldis = true
      	end
 end


end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :friendA %><br />
    <%= f.text_field :friendA %>
  </div>
  <div class="field">
    <%= f.label :friendB %><br />
    <%= f.text_field :friendB %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br />
    <%= f.check_box :accepted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/_user.html.erb
<div id="user_<%=friendship.id%>" class="friendship">
  <div class="friendship-info">
    <br>
    <h3><%= friendship.title %></h3>
    
    <span class="fl" ><%=  " Author: " + @user.first_name + " " + @user.last_name  %> </span>
    <span class="space"></span>
    <span class="fl space"><%= button_to "Edit", edit_friendship_path(friendship) , :class => "btn btn-primary btn-xs", :method => :get  %></span>    
    <span class="fl space"><%= button_to "Remove", delete_friendship_path(friendship) , :class => "btn btn-primary btn-xs", :method => :get  %></span>    
    <br>
    <br>
  </div>
  
  <p>
    <span><%= friendship.status %></span>
    <span><%= friendship.accepted %></span>
  </p>
</div>

app/views/friendships/edit.html.erb
<br>
<br>
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<br>
<br>
<h1>Listing friendships</h1>

<table>
  <tr>
    <th>Frienda</th>
    <th>Friendb</th>
    <th>Status</th>
    <th>Accepted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friendships.each do |friendship| %>
  <tr>
    <td><%= friendship.friendA %></td>
    <td><%= friendship.friendB %></td>
    <td><%= friendship.status %></td>
    <td><%= friendship.accepted %></td>
    <td><%= link_to 'Show', friendship %></td>
    <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
    <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<br>
<br>
<h1>Find People To Make Friendship</h1>
<%#= render 'form' %>
 <%# params[:listFriendShip] = true %>
 <% params[:current_user] = session[:user_id] %>
 <%= render @users %>
<br>
<br>
<%= button_to 'Back', articles_path, :class => "btn btn-primary btn-xs", :method => :get  %>

<script type="text/javascript">
	updateFriendshipText()
</script>

app/views/friendships/show.html.erb
<br>
<br>
<p id="notice"><%= notice %></p>

<p>
  <b>Frienda:</b>
  <%= @friendship.friendA %>
</p>

<p>
  <b>Friendb:</b>
  <%= @friendship.friendB %>
</p>

<p>
  <b>Status:</b>
  <%= @friendship.status %>
</p>

<p>
  <b>Accepted:</b>
  <%= @friendship.accepted %>
</p>


<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>