config/routes.rb
Blog::Application.routes.draw do
  
  resources :comments do
    member do
      get "edit", to: "comments#edit", as: "edit"
      get "delete", to: "comments#destroy", as: "delete"
      post "update",to: "comments#update", as: "update"
    end
    collection do
      get "show", to: "comments#show", as: "show"
    end
  end

  resources :users do
    member do
      get "edit"
      get "delete", to: "user#destroy", as: "delete"
      post "update"
    end
  end

  resources :articles do
    member do
      get "edit"
      get "delete", to: "articles#destroy", as: "delete"
      post "update"
    end
  end

  resources :friendships do
    member do
      get "block", to: "friendships#block", as: "block"
      get "delete", to: "friendships#destroy", as: "delete"
      get "make", to: "friendships#create", as: "make"

      get "accept", to: "friendships#accept", as: "accept"
      get "check", to: "friendships#check", as: "check"
    end
  end

  
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'page/index'
  root to: 'page#index'

  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag "application"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div id="user_header">
 <% if current_user %>
	<span class="topbar logged"> Logged in as <%= current_user.email %></span>
	
	
	<%= button_to "new post", new_article_path, :class => "topbar btn btn-primary btn-sm", :method => :get  %>

	<%= button_to "view post", articles_path, :class => "topbar btn btn-primary btn-sm", :method => :get  %>
	
 	<%= button_to "Make friendship", new_friendship_path, :class => "topbar btn btn-primary btn-sm", :method => :get  %>
 	
 	<%= button_to "Edit Profile", edit_user_path(current_user), :class => "toprightSec btn btn-primary btn-xs", :method => :get  %>
 	<%= button_to "Log Out", logout_path, :class => "topright btn btn-primary btn-xs", :method => :get  %>

 	
 <% else %>
 	<div class="logout_group">
 		<%= link_to "Sign Up", signup_path, :class => "toplink" %> 
 		<spam class="smttext">or</span>
 		<%= link_to "Log In", login_path , :class => "toplink"%>
 	</div>
 <% end %>
</div>

<% flash.each do |key, value| %>
 	<%= content_tag(:div, class: "alert alert-#{key}") do %>
		<p><%= value %></p>
	<% end %>
<% end %>


</body>
</html>